export const CRYPTO_GET_LIST = 'get_crypto_list'
export const CRYPTO_GET_LIST_LOADING = 'get_crypto_list_loading'
export const CRYPTO_GET_LIST_SUCCESS = 'get_crypto_list_success'
export const CRYPTO_CLEAR_LIST = 'clear_crypto_list'
export const CRYPTO_GET_LIST_ERROR = 'get_crypto_list_error'
export const CRYPTO_LIST_END_REACHED = 'crypto_list_end_reached'
export const GET_FAVORITES_LIST = 'get_favorites_list'
export const GET_FAVORITES_LIST_SUCCESS = 'get_favorites_list_success'
